// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADZtfMxAhITjIuAoQqF6QebR7cb18WcFE',
    appId: '1:460432828885:web:5f4b841538ff9a2ef9755c',
    messagingSenderId: '460432828885',
    projectId: 'pump-check',
    authDomain: 'pump-check.firebaseapp.com',
    storageBucket: 'pump-check.firebasestorage.app',
    measurementId: 'G-H8GN7R7EG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCgXOmVD_7ufr2-6BfY0MdZ2HqHb5_M8k',
    appId: '1:460432828885:android:836de855c40acb25f9755c',
    messagingSenderId: '460432828885',
    projectId: 'pump-check',
    storageBucket: 'pump-check.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQleg7qPk-3VtZRvt28EMB7ZZIo4bP7KA',
    appId: '1:460432828885:ios:ae47022807d990b1f9755c',
    messagingSenderId: '460432828885',
    projectId: 'pump-check',
    storageBucket: 'pump-check.firebasestorage.app',
    iosBundleId: 'com.example.flutterPumpCheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQleg7qPk-3VtZRvt28EMB7ZZIo4bP7KA',
    appId: '1:460432828885:ios:ae47022807d990b1f9755c',
    messagingSenderId: '460432828885',
    projectId: 'pump-check',
    storageBucket: 'pump-check.firebasestorage.app',
    iosBundleId: 'com.example.flutterPumpCheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADZtfMxAhITjIuAoQqF6QebR7cb18WcFE',
    appId: '1:460432828885:web:2e48775ec18c16fbf9755c',
    messagingSenderId: '460432828885',
    projectId: 'pump-check',
    authDomain: 'pump-check.firebaseapp.com',
    storageBucket: 'pump-check.firebasestorage.app',
    measurementId: 'G-RJQ4E67T0L',
  );
}
